package com.kevinjones.fitmasala.data.local.relation

/**
 * Read-only query projections. These are not entities — they exist so the
 * dashboard can ask SQLite for an aggregate instead of pulling every row into
 * memory and folding it in Kotlin.
 */

/**
 * All four sums are COALESCE'd in SQL, so an empty day returns zeroes rather
 * than nulls. A "no meals logged" day and a "0 kcal" day look identical here
 * on purpose — [mealCount] is what distinguishes them.
 */
data class DailyMacroTotals(
    val calories: Double,
    val proteinG: Double,
    val carbsG: Double,
    val fatG: Double,
    val fiberG: Double,
    val mealCount: Int,
)

/** One day's calories, for the trend strip. */
data class DailyCalories(
    val dayEpoch: Long,
    val calories: Double,
)

/**
 * The progressive-overload answer: what was done last time on this exercise.
 * `bestOneRepMax` ranks across rep ranges, so 100kg x 3 correctly beats
 * 80kg x 8 even though the second is more volume.
 */
data class ExercisePersonalBest(
    val exerciseId: Long,
    val bestWeightKg: Double,
    val bestOneRepMax: Double,
    val lastPerformedAt: Long,
    val totalSets: Int,
)

/** Session summary for the dashboard's middle section and the history list. */
data class SessionSummary(
    val sessionId: Long,
    val name: String,
    val startedAt: Long,
    val finishedAt: Long?,
    val dayEpoch: Long,
    val setCount: Int,
    val totalVolumeKg: Double,
)

/**
 * A dish the user eats often, collapsed across every time they logged it.
 *
 * Keyed on name rather than on a recipe id, because the same dish arrives by
 * several routes - typed by hand, generated by the chef, recognised from a photo
 * - and to the person eating it, it is one dish.
 */
data class FrequentMeal(
    val name: String,
    val nameLocal: String?,
    val region: String,
    val portionUnit: String,
    val timesLogged: Int,
    val lastEatenAt: Long,
    /** Averaged over past logs, so a one-off large portion does not set the default. */
    val avgCalories: Double,
    val avgProteinG: Double,
    val avgPortionQuantity: Double,
)

/** Per-day meal count, used to decide whether a day counts toward the streak. */
data class DayMealCount(
    val dayEpoch: Long,
    val mealCount: Int,
)
